{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{ezcss_require( 'owselectioncategorytype.css' )}
<div class="block">
<fieldset>
<legend>{'Options'|i18n( 'design/standard/class/datatype' )}</legend>
{section show=$class_attribute.content.options}
<table class="list" cellspacing="0">
<tr>
    <th class="tight">&nbsp;</th>
    <th colspan="2">{'Option'|i18n( 'design/standard/class/datatype' )}</th>
</tr>
{section name=Option loop=$class_attribute.content.options}
<tr>
    {* Remove. *}
    <td><input type="checkbox" name="ContentClass_owselectioncategory_option_remove_array_{$class_attribute.id}[{$Option:item.id}]" value="1" title="{'Select option for removal.'|i18n( 'design/standard/class/datatype' )}" /></td>

    {* Option. *}
    {if 0|eq($Option:item.group)}
        <td class="sub_group">|_</td>
    {/if}
    <td {if 1|eq($Option:item.group)}colspan="2" {/if}>
        <input class="box" type="text" name="ContentClass_owselectioncategory_option_name_array_{$class_attribute.id}[{$Option:item.id}]" value="{$Option:item.name|wash}" />
        <input type="hidden" name="ContentClass_owselectioncategory_groupoption_name_array_{$class_attribute.id}[{$Option:item.id}]" value="{$Option:item.group}" />
    </td>
</tr>
{/section}
</table>
{section-else}
<p>{'There are no options.'|i18n( 'design/standard/class/datatype' )}</p>
{/section}

{* Buttons. *}
{if $class_attribute.content.options}
<input class="button" type="submit" name="ContentClass_owselectioncategory_removeoption_button_{$class_attribute.id}" value="{'Remove selected'|i18n( 'design/standard/class/datatype' )}" title="{'Remove selected options.'|i18n( 'design/standard/class/datatype' )}" />
{else}
<input class="button-disabled" type="submit" name="ContentClass_owselectioncategory_removeoption_button_{$class_attribute.id}" value="{'Remove selected'|i18n( 'design/standard/class/datatype' )}" disabled="disabled" />
{/if}

<input class="button" type="submit" name="ContentClass_owselectioncategory_newgroupoption_button_{$class_attribute.id}" value="{'New group option'|i18n( 'design/standard/class/datatype' )}" title="{'Add a new group option.'|i18n( 'design/standard/class/datatype' )}" />
    <input class="button" type="submit" name="ContentClass_owselectioncategory_newoption_button_{$class_attribute.id}" value="{'New option'|i18n( 'design/standard/class/datatype' )}" title="{'Add a new option.'|i18n( 'design/standard/class/datatype' )}" />
</fieldset>
</div>
