{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let selected_id_array=cond( is_set( $#collection_attributes[$attribute.id] ), $#collection_attributes[$attribute.id].content, $attribute.content )}

{* Always set the .._selected_array_.. variable, this circumvents the problem when nothing is selected. *}
<input type="hidden" name="{$attribute_base}_ezselect_selected_array_{$attribute.id}" value="" />

<select name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]">
{section var=Options loop=$attribute.class_content.options}
{if 1|eq($Options.item.group)}
    <optgroup label="{$Options.item.name|wash( xhtml )}"></optgroup>
{else}
    <option value="{$Options.item.id}" {if $selected_id_array|contains( $Options.item.id )}selected="selected"{/if}>{$Options.item.name|wash( xhtml )}</option>
{/if}
{/section}
</select>
{/let}
{/default}
